# Generated by Django 5.1.4 on 2025-02-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posts_data",
            name="excerpt",
            field=models.TextField(default="null"),
        ),
        migrations.AddField(
            model_name="posts_data",
            name="slug",
            field=models.SlugField(default="null"),
        ),
    ]
