# Generated by Django 5.1.4 on 2025-02-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_posts_data_excerpt_posts_data_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts_data",
            name="date",
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="posts_data",
            name="slug",
            field=models.SlugField(default=""),
        ),
    ]
