# Generated by Django 5.1.4 on 2025-02-26 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_posts_data_date_alter_posts_data_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts_data",
            name="slug",
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
