# Generated by Django 5.1.4 on 2025-03-02 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_posts_data_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(default="None", max_length=50)),
                ("last_name", models.CharField(default="None", max_length=50)),
                ("age", models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name="posts_data",
            name="slug",
            field=models.SlugField(blank=True),
        ),
        migrations.AddField(
            model_name="posts_data",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="blog.author"
            ),
        ),
    ]
