# Generated by Django 5.1.4 on 2025-03-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_author_alter_posts_data_slug_posts_data_author"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="posts_data",
            new_name="Post",
        ),
        migrations.RemoveField(
            model_name="author",
            name="age",
        ),
        migrations.AddField(
            model_name="author",
            name="email",
            field=models.EmailField(default="None", max_length=254),
        ),
    ]
