# Generated by Django 5.1.4 on 2025-03-02 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_rename_posts_data_post_remove_author_age_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to="blog.author"
            ),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(max_length=20)),
                ("posts", models.ManyToManyField(related_name="tags", to="blog.post")),
            ],
        ),
    ]
