# Generated by Django 5.1.4 on 2025-03-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_alter_post_author_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="posts",
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(related_name="posts", to="blog.tag"),
        ),
    ]
